# Generated by Django 2.2 on 2022-12-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
