# Generated by Django 2.2 on 2022-12-05 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_api', '0003_auto_20221204_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user_profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
