# Generated by Django 2.2 on 2022-12-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_api', '0004_auto_20221204_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
