# Generated by Django 2.2 on 2022-12-05 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance_api', '0005_auto_20221205_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
